Kztek.Web/Controllers/HomeController.cs
using Kztek.Model.CustomModel;
using Kztek.Model.Models;
using Kztek.Service.Admin;
using Kztek.Web.Core.Functions;
using Kztek.Web.Core.Helpers;
using Kztek.Web.Core.Models;
using Kztek.Web.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Kztek.Web.Models;

namespace Kztek.Web.Controllers
{
    public class HomeController : Controller
    {
        private IMenuFunctionService _MenuFunctionService;

        public HomeController(IMenuFunctionService _MenuFunctionService)
        {
            this._MenuFunctionService = _MenuFunctionService;
        }

        [CheckSessionLogin]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Header(string controllerName = "", string actionName = "")
        {
            var list = new List<MenuFunction>();

            if (CacheLayer.Exists(ConstField.AllListMenuFunctionCache))
            {
                list = CacheLayer.Get<List<MenuFunction>>(ConstField.AllListMenuFunctionCache);
            }
            else
            {
                list = _MenuFunctionService.GetAllActive().ToList();
                CacheLayer.Add(ConstField.AllListMenuFunctionCache, list, ConstField.TimeCache);
            }

            var obj = _MenuFunctionService.GetByControllerAction(controllerName, actionName);

            return PartialView(obj);
        }

        /// <summary>
        /// Thanh điều hướng
        /// </summary>
        /// <param name="controller">Tên controller</param>
        /// <param name="action">Tên action</param>
        /// <returns></returns>
        public PartialViewResult Breadcrumb(string controller = "", string action = "")
        {
            //Danh sách menu
            var list = new List<MenuFunction>();
            if (CacheLayer.Exists(ConstField.AllListMenuFunctionCache))
            {
                list = CacheLayer.Get<List<MenuFunction>>(ConstField.AllListMenuFunctionCache);
            }
            else
            {
                list = _MenuFunctionService.GetAllActive().ToList();
                CacheLayer.Add(ConstField.AllListMenuFunctionCache, list, ConstField.TimeCache);
            }

            //Khai báo biến
            List<string> MenuName = new List<string>();

            var obj = list.FirstOrDefault(n => n.ControllerName.Equals(controller) && n.ActionName.Equals(action));
            if (obj != null)
            {
                if (!string.IsNullOrEmpty(obj.Breadcrumb))
                {
                    string[] id = obj.Breadcrumb.Split(new string[] { '/' + obj.Id }, StringSplitOptions.RemoveEmptyEntries);
                    if (id != null)
                    {
                        string[] ids = id[0].Split(new Char[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
                        if (ids != null)
                        {
                            foreach (var item in ids)
                            {
                                var Name = _MenuFunctionService.getById(item);
                                if (Name != null)
                                {
                                    MenuName.Add(Name.MenuName + "," + controller.ToString());
                                }
                            }
                        }
                    }
                }
            }

            ViewBag.ObjName = (obj != null && !string.IsNullOrWhiteSpace(obj.MenuName)) ? obj.MenuName : "";
            ViewBag.listMenu = MenuName;

            return PartialView();
        }

        /// <summary>
        /// Danh sách sidebar
        /// </summary>
        /// <param name="actionName">Tên action</param>
        /// <param name="controllerName">Tên controller</param>
        /// <param name="openTab">Mở tab lớn khi có chọn con</param>
        /// <returns></returns>
        public PartialViewResult Sidebar(string actionName = "Index", string controllerName = "Home", string openTab = "")
        {
            //All menuFunction
            //var list = CacheLayer.Get<List<MenuFunction>>(ConstField.AllListMenuFunctionCache);
            //if(list==null)
            //{
            //    list = _MenuFunctionService.GetAllActive().ToList();
            //    CacheLayer.Add(ConstField.AllListMenuFunctionCache, list, ConstField.TimeCache);
            //}
            // Current User
            var user = GetCurrentUser.GetUser();

            // get all Role menu buy User
            var model = new List<MenuFunction>();
            if (user != null)
            {
                model = _MenuFunctionService.GetAllMenuByPermisstion(user.Id, user.Admin).Distinct().ToList();
            }

            var pageModel = new PageNameModel
            {
                ControllerName = controllerName,
                ActionName = actionName,
                OpenMenu = openTab
            };

            ViewBag.PageModel = pageModel;
            return PartialView(model);
        }

        public PartialViewResult Child(MenuFunction itemMenu, List<MenuFunction> listMenu, List<MenuFunction> AllMenu)
        {

            ViewBag.ItemMenu = itemMenu;
            ViewBag.AllMenuPermisstion = AllMenu;

            return PartialView(listMenu);
        }

        /// <summary>
        /// Chứa danh sách các actions có trong hệ thống + phân quyền
        /// </summary>
        /// <param name="ControllerName">Tên controller</param>
        /// <param name="ActionName">Tên action</param>
        /// <param name="id">Id đối tượng thao tác</param>
        /// <param name="pageNumber">Trang hiện tại</param>
        /// <returns></returns>
        public PartialViewResult Actions(string ControllerName, string ActionName, string id = "", int pageNumber = 1)
        {
            ViewBag.ControllerName = ControllerName;
            ViewBag.ActionName = ActionName;
            ViewBag.Id = id;
            ViewBag.PN = pageNumber;

            return PartialView();
        }

        /// <summary>
        /// Giao diện footer
        /// </summary>
        /// <returns></returns>
        public PartialViewResult Footer()
        {
            return PartialView();
        }

        public PartialViewResult Buttons(string controller, string action, string url, int pageNumber = 1)
        {
            ViewBag.Controller = controller;
            ViewBag.Action = action;
            ViewBag.url = url;
            ViewBag.PN = pageNumber;
            return PartialView();
        }


        public JsonResult DeleteCached()
        {
            bool isSucccess = true;
            try
            {
                CacheLayer.ClearAll();
            }
            catch (Exception)
            {
                isSucccess = false;
            }
            return Json(isSucccess, JsonRequestBehavior.AllowGet);
        }
    }
}

Kztek.Web/Controllers/UserController.cs
using Kztek.Model.CustomModel;
using Kztek.Model.Models;
using Kztek.Service.Admin;
using Kztek.Web.Core.Extensions;
using Kztek.Web.Core.Functions;
using Kztek.Web.Core.Helpers;
using Kztek.Web.Core.Models;
using Kztek.Web.Attributes;
using Kztek.Web.Models;
using System;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace Kztek.Web.Controllers
{
    public class UserController : Controller
    {
        #region Khai báo services

        /// <summary>
        /// Khai báo services
        /// </summary>
        private IUserService _UserService;

        private IMenuFunctionService _MenuFunctionService;
        private IUserRoleService _UserRoleService;
        private IRoleService _RoleService;
        private IUserConfigService _UserConfigService;

        public UserController(IUserService _UserService, IMenuFunctionService _MenuFunctionService, IUserRoleService _UserRoleService, IRoleService _RoleService, IUserConfigService _UserConfigService)
        {
            this._UserService = _UserService;
            this._MenuFunctionService = _MenuFunctionService;
            this._UserRoleService = _UserRoleService;
            this._RoleService = _RoleService;
            this._UserConfigService = _UserConfigService;
        }

        #endregion Khai báo services

        private static string url = "";

        #region Danh sách

        /// <summary>
        /// Danh sách
        /// </summary>
        /// <modified>
        /// Author              Date            Comments
        /// TrungNQ             10/12/2016      Tạo mới
        /// </modified>
        /// <param name="key">Từ khóa</param>
        /// <param name="active">Trạng thái</param>
        /// <param name="page">Trang hiện tại</param>
        /// <returns></returns>
        [CheckSessionLogin]
        [CheckAuthorize]
        public ActionResult Index(string key, int page = 1)
        {
            //Khai báo
            int pageSize = 2;

            //Lấy danh sách phân trang
            var list = _UserService.GetAllPagingByFirst(key, page, pageSize);

            //Đổ lên grid
            var gridModel = PageModelCustom<User>.GetPage(list, page, pageSize);

            //ViewBag
            ViewBag.keyValue = key;

            url = Request.Url.PathAndQuery;

            //Đưa ra giao diện
            return View(gridModel);
        }
        public PartialViewResult RoleList(string userId)
        {
            var roles = _RoleService.GetAllByUserId(userId);
            return PartialView(roles);
        }
        #endregion Danh sách

        #region Thêm mới

        /// <summary>
        /// Giao diện thêm mới
        /// </summary>
        /// <modified>
        /// Author          Date            Comments
        /// TrungNQ         04/08/2017      Tạo mới
        /// </modified>
        /// <returns></returns>
        [CheckSessionLogin]
        [CheckAuthorize]
        [HttpGet]
        public ActionResult Create()
        {
            //ViewBag.Selected = "";

            //ViewBag.urlValue = url;

            return View();
        }

        /// <summary>
        /// Thêm mới
        /// </summary>
        /// <modified>
        /// Author          Date            Comments
        /// TrungNQ         04/08/2017      Tạo mới
        /// </modified>
        /// <param name="obj">Đối tượng</param>
        /// <param name="rolevalues">Giá trị quyền</param>
        /// <param name="FileUpload">File Upload</param>
        /// <param name="SaveAndCountinue">Tiếp tục thêm</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(User obj, string repass, string rolevalues, HttpPostedFileBase file, bool SaveAndCountinue = false)
        {
            //
            ViewBag.Selected = rolevalues;
            ViewBag.urlValue = url;

            //Kiểm tra
            if (!ModelState.IsValid)
            {
                return View(obj);
            }

            var isExisted = _UserService.GetByUserName(obj.Username);
            if (isExisted != null)
            {
                ModelState.AddModelError("Username", "Tên đăng nhập đã tồn tại");
                return View(obj);
            }

            //Gán giá trị
            obj.Id = Common.GenerateId();
            obj.DateCreated = DateTime.Now;
            obj.PasswordSalat = Guid.NewGuid().ToString();

            if (!string.IsNullOrWhiteSpace(obj.Password))
            {
                if (!string.IsNullOrWhiteSpace(repass))
                {
                    if (obj.Password.Equals(repass))
                    {
                        obj.Password = obj.Password.PasswordHashed(obj.PasswordSalat);
                    }
                    else
                    {
                        ModelState.AddModelError("repass", "Vui lòng nhập lại đúng mật khẩu.");
                        return View(obj);
                    }
                }
                else
                {
                    ModelState.AddModelError("repass", "Vui lòng nhập lại mật khẩu.");
                    return View(obj);
                }
            }
            else
            {
                obj.Password = "";
                obj.Password = obj.Password.PasswordHashed(obj.PasswordSalat);
            }

            //Thêm mới danh sách quyền
            if (!string.IsNullOrWhiteSpace(rolevalues))
            {
                var ids = rolevalues.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                if (ids.Any())
                {
                    foreach (var id in ids)
                    {
                        var UserRole = new UserRole();
                        UserRole.Id = Common.GenerateId();
                        UserRole.RoleId = id;
                        UserRole.UserId = obj.Id;

                        _UserRoleService.Create(UserRole);
                    }
                }
            }


            //File upload
            if (file != null)
            {
                var extension = Path.GetExtension(file.FileName) ?? "";
                var fileName = Path.GetFileName(string.Format("{0}{1}", StringUtil.RemoveSpecialCharactersVn(file.FileName.Replace(extension, "")).GetNormalizeString(), extension));
                obj.UserAvatar = string.Format("{0}{1}", ConfigurationManager.AppSettings["uploadfolder"], fileName);
            }

            //Thực hiện thêm mới
            var result = _UserService.Create(obj);
            if (result.isSuccess)
            {
                //FunctionHelper.UploadImage(FileUpload, Server.MapPath(ConfigurationManager.AppSettings["uploadfolder"]));

                if (SaveAndCountinue)
                {
                    TempData["Success"] = result.Message;
                    return RedirectToAction("Create");
                }

                return Redirect(url);
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(obj);
            }
        }

        #endregion Thêm mới

        #region Cập nhật

        /// <summary>
        /// Giao diện cập nhật
        /// </summary>
        /// <modified>
        /// Author          Date            Comments
        /// TrungNQ         04/08/2017      Tạo mới
        /// </modified>
        /// <param name="id">Id bản ghi</param>
        /// <param name="pageNumber">Trang hiện tại</param>
        /// <returns></returns>
        [CheckSessionLogin]
        [CheckAuthorize]
        [HttpGet]
        public ActionResult Update(string id)
        {
            var str = "";

            var obj = _UserService.GetById(id);

            var list = _UserRoleService.GetAllByUserId(obj.Id);
            if (list.Any())
            {
                foreach (var item in list)
                {
                    str += item.RoleId + ",";
                }
            }

            ViewBag.Selected = str;
            ViewBag.urlValue = url;

            return View(obj);
        }

        /// <summary>
        /// Cập nhật
        /// </summary>
        /// <modified>
        /// Author          Date            Comments
        /// TrungNQ         04/08/2017      Tạo mới
        /// </modified>
        /// <param name="obj">Đối tượng</param>
        /// <param name="objId">Id bản ghi hiện tại</param>
        /// <param name="pass">Mật khẩu</param>
        /// <param name="rolevalues">Danh sách quyền</param>
        /// <param name="FileUpload">File Upload</param>
        /// <param name="pageNumber">Trang hiện tại</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Update(User obj, string pass, string repass, string rolevalues, HttpPostedFileBase FileUpload)
        {
            //
            ViewBag.urlValue = url;
            ViewBag.Selected = rolevalues;

            //Kiểm tra
            var oldObj = _UserService.GetById(obj.Id);
            
            if (oldObj == null)
            {
                ViewBag.Error = "Bản ghi không tồn tại";
                return View(obj);
            }

            if (!ModelState.IsValid)
            {
                return View(oldObj);
            }

            //var isExisted = _UserService.GetByUserName_Id(oldObj.Username, oldObj.Id.ToString());
            //if (isExisted != null)
            //{
            //    ModelState.AddModelError("Username", "Tên đăng nhập đã tồn tại");
            //    return View(oldObj);
            //}

            //Gán giá trị
            //oldObj.Username = obj.Username;
            //oldObj.Active = obj.Active;
            oldObj.Admin = obj.Admin;

            //Kiểm tra là tài khoản admin
            var currentUser = GetCurrentUser.GetUser();
            if (currentUser.Admin)
            {
                if (oldObj.Id.ToString().Equals(currentUser.Id.ToString()))
                {
                    //oldObj.isAdmin = obj.isAdmin;

Kztek.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Kztek.Web/Views/Home/Actions.cshtml
@using Kztek.Web.Attributes

@{
    var controller = (string)ViewBag.ControllerName;
    var action = (string)ViewBag.ActionName;
    var id = ViewBag.Id;
    int pn = ViewBag.PN;
}

@{
    //Nút thêm mới
    if (action.Equals("Create"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="@Url.Action(action, controller)" class="btn btn-xs btn-primary btn-white btn-bold">
                <i class=" fa fa-plus"></i> Thêm mới
            </a>
        }
    }

    //Nút cập nhật
    if (action.Equals("Update"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="@Url.Action(action, controller, new { @id = id , pageNumber = pn})" class="green" title="Cập nhật">
                <i class="ace-icon fa fa-pencil bigger-120"></i>
            </a>
        }
    }

    //Nút xóa
    if (action.Equals("Delete"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="javascript:void(0)" class="btnDelete red" idata="@id" title="Xóa" na>
                <i class="ace-icon fa fa-trash bigger-120"></i>
            </a>
        }
    }

    //Nút xóa nhiều
    if (action.Equals("MultiDelete"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="javascript:void(0)" class="btnMultiDelete btn btn-danger btn-white btn-xs btn-bold">
                <i class=" fa fa-trash"></i> Xóa
            </a>
        }
    }

    //Nút active
    if (action.Equals("Active"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="javascript:void(0)" class="btn btn-xs btn-primary" id="btnDuyet" style="float:right;">
                <i class=" fa fa-check"></i> Cập nhật
            </a>
        }
    }

    //Nút phân quyền
    if (action.Equals("Authorize"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="@Url.Action(action, controller, new { @id = id ,pageNumber=pn})" class="blue" title="Cập nhật">
                <i class="ace-icon fa fa-plug bigger-120"></i>
            </a>
        }
    }

    if (action.Equals("RestoreDefaultPass"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="javascript:void(0)" class="btnRes blue" idata="@id" title="Phục hồi mật khẩu">
                <i class="ace-icon fa fa-recycle bigger-120"></i>
            </a>
        }
    }

    //Restore
    if (action.Equals("Restore"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="javascript:void(0)" class="btnRestore blue" idata="@id" title="Phục hồi">
                <i class="ace-icon fa fa-refresh bigger-120"></i>
            </a>
        }
    }

    if (action.Equals("PrintFile"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="javascript:void(0)" class="btnPrintFile grey" idata="@id" title="In ấn">
                <i class="ace-icon fa fa-print bigger-120"></i>
            </a>
        }
    }

    //PerDel
    if (action.Equals("PerDel"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <a href="javascript:void(0)" class="btnPerDel red" idata="@id" title="Xóa vĩnh viễn">
                <i class="ace-icon fa fa-database bigger-120"></i>
            </a>
        }
    }

    //Export
    if (action.Equals("Export"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <button class="btn btn-primary btn-white btn-xs btn-bold" type="button" name="btnExport">
                <i class="fa fa-file green" aria-hidden="true"></i>
                Export
            </button>
        }
    }

    //Import
    if (action.Equals("Import"))
    {
        CheckAuthorizeAction.Instance.CheckPemission(controller, action);
        if (CheckAuthorizeAction.Instance.Check)
        {
            <button class="btn btn-primary btn-white btn-xs btn-bold" type="button" name="btnImport">
                <i class="fa fa-file green"></i>
                Import
            </button>
        }
    }

    //Index
    if (action.Equals("Index"))
    {
        if (controller.Contains("Report"))
        {
            <a href="@Url.Action(controller, "Report")" class="btn btn-primary btn-white btn-xs btn-bold" type="submit">
                <i class="fa fa-refresh green" aria-hidden="true"></i>
                Reset
            </a>
        }
        else
        {
            <a href="@Url.Action(action, controller)" class="btn btn-primary btn-white btn-xs btn-bold" type="submit">
                <i class="fa fa-refresh green" aria-hidden="true"></i>
                Reset
            </a>
        }
    }

    //Search
    if (action.Equals("Search"))
    {
        <button class="btn btn-xs btn-primary" type="button" name="btnFilter">
            <i class="fa fa-search"></i>
            Tìm kiếm
        </button>
    }

    if (action.Equals("Print"))
    {
        <button type="button" class="btn btn-primary btn-white btn-xs btn-bold" id="btnPrintFile">
            <i class="fa fa-file-pdf-o green"></i>
            In
        </button>
    }
}

Kztek.Web/Views/Home/Breadcrumb.cshtml
@{
    var obj = ViewBag.ObjName;
    var list = (List<string>)ViewBag.listMenu;
}

<ul class="breadcrumb">
    <li>
        <i class="ace-icon fa fa-home home-icon"></i>
        <a href="/">Trang chủ</a>
    </li>
    @if (list.Any())
    {
        foreach (var item in list)
        {
            var a = item.Split(',');
            <li>
                @Html.ActionLink(a[0],"Index", a[1])
            </li>
        }
    }
    <li class="active">@obj</li>
</ul><!-- /.breadcrumb -->

Kztek.Web/Views/Home/Buttons.cshtml
@if (ViewBag.Action == "Create")
{
    <div class="ace-settings-container" id="ace-settings-container" style="position: fixed; top: 155px;">
        <div class="btn btn-app btn-xs btn-grey ace-settings-btn open" id="ace-settings-btn">
            <i class="ace-icon fa fa-cog bigger-130"></i>
        </div>

        <div class="ace-settings-box clearfix open" id="ace-settings-box">
            <!-- /.pull-left -->
            <div class="bg-rightbox">
                <div class="clearfix lineButton">
                    <div class="col-md-12 input-group">
                        <button class="btn btn-success" type="submit" id="Countinue">
                            <i class="ace-icon fa fa-refresh bigger-110"></i>
                            Lưu
                        </button>
                        <button class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            Lưu và thoát
                        </button>
                        <button class="btn" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            Nhập lại
                        </button>
                        <a href="@ViewBag.url" class="btn btn-yellow">
                            <i class="ace-icon fa fa-chevron-circle-left bigger-110"></i>
                            Quay lại
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.pull-left -->
        </div><!-- /.ace-settings-box -->
    </div>
}

@if (ViewBag.Action == "Update")
{
    <div class="ace-settings-container" id="ace-settings-container" style="position: fixed; top: 155px;">
        <div class="btn btn-app btn-xs btn-grey ace-settings-btn open" id="ace-settings-btn">
            <i class="ace-icon fa fa-cog bigger-130"></i>
        </div>

        <div class="ace-settings-box clearfix open" id="ace-settings-box">
            <!-- /.pull-left -->
            <div class="bg-rightbox">
                <div class="clearfix lineButton">
                    <div class="col-md-12 input-group">
                        <button class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            Lưu và thoát
                        </button>
                        <button class="btn" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            Nhập lại
                        </button>
                        <a href="@ViewBag.url" class="btn btn-yellow">
                            <i class="ace-icon fa fa-chevron-circle-left bigger-110"></i>
                            Quay lại
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.pull-left -->
        </div><!-- /.ace-settings-box -->
    </div>
}

Kztek.Web/Views/Home/Child.cshtml
@using Kztek.Model.Models
@using Kztek.Web.Attributes
@model List<MenuFunction>
@{
    var allMenu = (List<MenuFunction>)ViewBag.AllMenuPermisstion;
    var ItemMenu = (MenuFunction)ViewBag.ItemMenu;

}
@if (Model.Any())
{
    <ul class="submenu">
        @foreach (var item in Model)
        {
            var child = allMenu.Where(c => c.ParentId == item.Id && c.MenuType == "1").ToList();
            <li class="@string.Format("{0}", (ItemMenu!=null &&!string.IsNullOrWhiteSpace(ItemMenu.Breadcrumb)&& ItemMenu.Breadcrumb.Contains(item.Breadcrumb)) ? "open active" : "")">
                <a href="@string.Format("{0}",child.Any()?"javascript:void(0)": Url.Action(item.ActionName,item.ControllerName))" class="@string.Format("{0}",child.Any()?"dropdown-toggle":"")">
                    <i class="menu-icon fa @item.Icon"></i>
                    <span class="menu-text">
                        @item.MenuName
                    </span>
                    @if (child.Any())
                    {
                        <b class="arrow fa fa-angle-down"></b>
                    }
                </a>
                @if (child.Any())
                {
                    <b class="arrow"></b>
                    @Html.Action("Child", "Home", new { itemMenu = ItemMenu, listMenu = child, AllMenu = allMenu })
                }

            </li>
        }
    </ul>
}

Kztek.Web/Views/Home/Header.cshtml
@using Kztek.Web.Core.Functions
@using Kztek.Web.Models
@using Kztek.Web.Core.Extensions

@model Kztek.Model.Models.MenuFunction

@{
    var user = GetCurrentUser.GetUser();
    var controller = (string)ViewBag.Controller;
    var action = (string)ViewBag.Action;
}

<div class="navbar-container ace-save-state" id="navbar-container">
    <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
        <span class="sr-only">Toggle sidebar</span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>
    </button>

    <div class="navbar-header pull-left">
        <a href="@Url.Action("Index","Home")" class="navbar-brand">
            <small>
                <i class="fa fa-leaf"></i>
                Kztek - Hệ thống quản trị
            </small>
        </a>
    </div>

    <div class="navbar-header">
    </div>

    <div class="navbar-buttons navbar-header pull-right" role="navigation">
        <ul class="nav ace-nav">
            @if (user != null)
            {
                <li class="purple dropdown-modal">
                    <a name="btnDeleteCached" href="javascript:void(0)" title="Xóa cached">
                        <i class="ace-icon fa fa-tasks"></i>
                    </a>
                    
                </li>
                <li class="light-blue dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="@user.UserAvatar.ImagePathThumb(40,40)" alt="" />
                        <span class="user-info">
                            <small>Welcome,</small>
                            @user.Name
                        </span>

                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>

                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="@Url.Action("UserProfile", "User", new { @id = user.Id })">
                                <i class="ace-icon fa fa-user"></i>
                                Tài khoản
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="@Url.Action("Logout", "Login")">
                                <i class="ace-icon fa fa-power-off"></i>
                                Đăng xuất
                            </a>
                        </li>
                    </ul>
                </li>
            }
        </ul>
    </div>
</div><!-- /.navbar-container -->