Kztek.Web/Controllers/RoleController.cs
using Kztek.Model.CustomModel;
using Kztek.Model.Models;
using Kztek.Service.Admin;
using Kztek.Web.Core.Functions;
using Kztek.Web.Core.Helpers;
using Kztek.Web.Core.Models;
using Kztek.Web.Attributes;
using Kztek.Web.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Kztek.Web.Controllers
{
    public class RoleController : Controller
    {
        #region Khai báo services

        private IRoleService _RoleService;
        private IRoleMenuService _RoleMenuService;
        private IMenuFunctionService _MenuFunctionService;
        private IUserRoleService _UserRoleService;

        public RoleController(IRoleService _RoleService, IRoleMenuService _RoleMenuService, IMenuFunctionService _MenuFunctionService, IUserRoleService _UserRoleService)
        {
            this._RoleService = _RoleService;
            this._RoleMenuService = _RoleMenuService;
            this._MenuFunctionService = _MenuFunctionService;
            this._UserRoleService = _UserRoleService;
        }

        #endregion Khai báo services

        private static string url = "";

        #region Danh sách

        [CheckSessionLogin]
        [CheckAuthorize]
        public ActionResult Index(string key)
        {
            var list = _RoleService.GetAllByFirst(key);

            url = Request.Url.PathAndQuery;

            return View(list);
        }

        #endregion Danh sách

        #region Thêm mới

        [HttpGet]
        [CheckSessionLogin]
        [CheckAuthorize]
        public ActionResult Create()
        {
            ViewBag.Selected = "";
            ViewBag.urlValue = url;

            ViewBag.MenuFunctionList = _MenuFunctionService.GetAllActive().ToList();
            return View();
        }

        public ActionResult Create(Role obj, string menufunctionvalues, bool SaveAndCountinue = false)
        {
            //
            ViewBag.Selected = menufunctionvalues;
            ViewBag.urlValue = url;

            //Kiểm tra
            if (!ModelState.IsValid)
            {
                return View(obj);
            }

            //Gán giá trị
            obj.Id = Common.GenerateId();

            //Thêm danh sách cây menu
            if (!string.IsNullOrWhiteSpace(menufunctionvalues))
            {
                var ids = menufunctionvalues.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                if (ids.Any())
                {
                    foreach (var id in ids)
                    {
                        RoleMenu objRoleMenu = new RoleMenu();
                        objRoleMenu.Id = Common.GenerateId();
                        objRoleMenu.RoleId = obj.Id;
                        objRoleMenu.MenuId = id;
                        _RoleMenuService.Create(objRoleMenu);
                    }
                }
            }

            //Thực hiện thêm mới
            var result = _RoleService.Create(obj);
            if (result.isSuccess)
            {
                if (SaveAndCountinue)
                {
                    TempData["Success"] = result.Message;
                    return RedirectToAction("Create");
                }

                return RedirectToAction("Index");
            }
            else
            {
                return View(obj);
            }
        }

        public JsonResult CreateRole(Role obj, string lstId)
        {
            var report = new MessageReport();
            obj.Id = Common.GenerateId();

            if (ModelState.IsValid)
            {
                report = _RoleService.Create(obj);
            }

            if (report.isSuccess)
            {
                string[] ids = lstId.Split(new Char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                if (ids != null)
                {
                    foreach (var item in ids)
                    {
                        RoleMenu objRoleMenu = new RoleMenu();
                        objRoleMenu.Id = Common.GenerateId();
                        objRoleMenu.RoleId = obj.Id;
                        objRoleMenu.MenuId = item;
                        _RoleMenuService.Create(objRoleMenu);
                    }
                }
            }

            return Json(report, JsonRequestBehavior.AllowGet);
        }

        #endregion Thêm mới

        #region Cập nhật

        [HttpGet]
        [CheckSessionLogin]
        [CheckAuthorize]
        public ActionResult Update(string id)
        {
            string str = "";
            var obj = _RoleService.GetById(id);

            var t = _RoleMenuService.GetAllByRoleId(id).ToList();
            if (t != null && t.Any())
            {
                foreach (var item in t)
                {
                    str += item.MenuId + ",";
                }
            }

            ViewBag.Selected = str;
            ViewBag.urlValue = url;

            return View(obj);
        }

        [HttpPost]
        public ActionResult Update(Role obj, string menufunctionvalues)
        {
            //
            ViewBag.Selected = menufunctionvalues;
            ViewBag.urlValue = url;

            //Kiểm tra
            var oldObj = _RoleService.GetById(obj.Id);
            if (oldObj == null)
            {
                ViewBag.Error = "Bản ghi đã tồn tại";
                return View(obj);
            }

            if (!ModelState.IsValid)
            {
                return View(oldObj);
            }

            //Gán giá trị
            oldObj.RoleName = obj.RoleName;
            oldObj.Description = obj.Description;
            oldObj.Active = obj.Active;

            //Cập nhật lại danh sách menu
            var list = _RoleMenuService.GetAllByRoleId(obj.Id).ToList();
            if (list.Any())
            {
                foreach (var item in list)
                {
                    _RoleMenuService.DeleteById(item.Id);
                }
            }

            if (!string.IsNullOrWhiteSpace(menufunctionvalues))
            {
                string[] ids = menufunctionvalues.Split(new Char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                if (ids != null)
                {
                    foreach (var item in ids)
                    {
                        RoleMenu objRoleMenu = new RoleMenu();
                        objRoleMenu.Id = Common.GenerateId();
                        objRoleMenu.RoleId = oldObj.Id;
                        objRoleMenu.MenuId = item;
                        _RoleMenuService.Create(objRoleMenu);
                    }
                }
            }

            //Thực hiện cập nhật
            var result = _RoleService.Update(oldObj);
            if (result.isSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Có lỗi xảy ra");
                return View(oldObj);
            }
        }

        //[HttpPost]
        //public ActionResult Update(Role obj)
        //{
        //    //ViewBag.MenuFunctionList = _MenuFunctionService.GetAllActive().ToList();
        //    if (ModelState.IsValid)
        //    {
        //        bool isSuccess = _RoleService.Update(obj);
        //        if (isSuccess)
        //        {
        //            MessageReport report = new MessageReport(true, "Cập nhật thành công");
        //            WriteLog.Write(report, GetCurrentUser.GetUser(), obj.Id, obj.RoleName, "Role");

        //            FunctionHelper.ClearCache(ConstField.ListRoleMenu, obj.Id);

        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            ModelState.AddModelError("", "Có lỗi xảy ra");
        //            return View(obj);
        //        }
        //    }
        //    return View(obj);
        //}

        public JsonResult UpdateRole(string lstId, string RoleId)
        {
            bool isSuccess = false;
            try
            {
                var list = _RoleMenuService.GetAllByRoleId(RoleId).ToList();
                if (list.Any())
                {
                    foreach (var item in list)
                    {
                        _RoleMenuService.DeleteById(item.Id);
                    }
                }

                if (!string.IsNullOrWhiteSpace(lstId))
                {
                    string[] ids = lstId.Split(new Char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                    if (ids != null)
                    {
                        foreach (var item in ids)
                        {
                            RoleMenu objRoleMenu = new RoleMenu();
                            objRoleMenu.Id = Common.GenerateId();
                            objRoleMenu.RoleId = RoleId;
                            objRoleMenu.MenuId = item;
                            isSuccess = _RoleMenuService.Create(objRoleMenu);
                        }
                    }
                }
                else
                {
                    isSuccess = true;
                }

                if (isSuccess)
                {
                    FunctionHelper.ClearCache(ConstField.ListRoleMenu, RoleId);
                }
            }
            catch (Exception ex)
            {
                isSuccess = false;
                throw ex;
            }

            return Json(isSuccess, JsonRequestBehavior.AllowGet);
        }

        #endregion Cập nhật

        #region Xóa

        [CheckAuthorize]
        public JsonResult Delete(string id)
        {
            var obj = _RoleService.GetById(id);

            var report = _RoleService.DeleteById(id);
            if (report.isSuccess)
            {
                FunctionHelper.ClearCache(ConstField.ListRoleMenu, id);

                var listRoleMenu = _RoleMenuService.GetAllByRoleId(id);
                if (listRoleMenu.Any())
                {
                    foreach (var item in listRoleMenu.ToList())

Kztek.Web/Views/Role/Child.cshtml
@model List<Kztek.Model.Models.MenuFunction>

@{
    string selected = (string)ViewBag.Selected;
}

@if (Model.Any())
{
    <ul>
        @foreach (var item in Model.OrderBy(n => n.OrderNumber))
        {
            if (selected.Contains(item.Id.ToString()))
            {
                <li>
                    <label class="line-height-250">
                        <input type="checkbox" name="chkCheckBox" id="chkCheckBox" value="@item.Id" class="ace chkCheckBox" checked />
                        <span class="lbl"> </span>
                    </label>
                    <span class="liMenuFunction" style="font-weight: bold;">
                        @item.MenuName
                    </span>
                    @Html.Action("Child", new { parentId = item.Id.ToString(), selectedId = selected })
                </li>
            }
            else
            {
                <li>
                    <label class="line-height-250">
                        <input type="checkbox" name="chkCheckBox" id="chkCheckBox" value="@item.Id" class="ace chkCheckBox" />
                        <span class="lbl"> </span>
                    </label>
                    <span class="liMenuFunction" style="font-weight: bold;">
                        @item.MenuName
                    </span>
                    @Html.Action("Child", new { parentId = item.Id.ToString(), selectedId = selected })
                </li>
            }
        }
    </ul>
}

Kztek.Web/Views/Role/Create.cshtml
@model Kztek.Model.Models.Role

@{
    ViewBag.Title = "Thêm mới vai trò";
    string selected = (string)ViewBag.Selected;
}

<div class="page-header">
    <h1>
        @ViewBag.Title
    </h1>
</div>
<div class="row">
    @if (TempData["Success"] != null)
    {
        <strong style="color:green">@TempData["Success"]</strong>
    }
    <strong style="color:red">@ViewBag.Error</strong>
</div>
<div class="row">
    <div class="col-md-7 col-xs-12">
        <h3 class="header smaller lighter blue">Thông tin cơ bản</h3>
        @using (Html.BeginForm("Create", "Role", FormMethod.Post, new { encType = "multipart/form-data", @class = "form-horizontal", @role = "form", @id = "frmCreateRole" }))
        {
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Tên vai trò <span style="color:red">*</span></label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.RoleName, new { @class = "form-control", @placeholder = "Tên vai trò" })
                    @Html.ValidationMessageFor(n => n.RoleName, "", new { @class = "text-danger" })
                    @Html.Hidden("SaveAndCountinue", false)
                    @Html.Hidden("menufunctionvalues", selected)
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Mô tả </label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Description, new { @class = "form-control", @placeholder = "Mô tả" })
                    @Html.ValidationMessageFor(n => n.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Kích hoạt </label>
                <div class="col-sm-6">
                    <label class="line-height-250">
                        @Html.CheckBoxFor(n => n.Active, new { @class = "ace", @checked = "true" })
                        <span class="lbl"></span>
                    </label>
                </div>
            </div>

            @Html.Action("Buttons", "Home", new { controller = "Role", action = "Create", url = ViewBag.urlValue })
        }
    </div>
    <div class="col-md-5 col-xs-12">
        <h3 class="header smaller lighter blue">Danh mục hệ thống</h3>
        <div style="overflow-y:scroll;height:400px;position:relative">
            @Html.Action("MenuFunctionList", "Role", new { str = selected })
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $(".chkCheckBox").click(function () {
                var cmd = $(this);
                cmd.parent().parent().find('ul li input[type=checkbox]').prop('checked', cmd.is(':checked'));
            });

            $("span.liMenuFunction").click(function () {
                var cmd = $(this);
                cmd.parent().find('ul li span.liMenuFunction').parent().parent().fadeToggle();
            });

            $("#Countinue").click(function () {
                $("#SaveAndCountinue").val('true');
            });

            $("#frmCreateRole").submit(function () {
                var str = "";
                $("input[name='chkCheckBox']").each(function () {
                    var cmd = $(this);
                    var id = cmd.prop("value");
                    if ($(this).is(":checked")) {
                        str = str + id + ",";
                    }
                });
                $("#menufunctionvalues").val(str);
            });
        });
    </script>
}

Kztek.Web/Views/Role/Index.cshtml
@using Kztek.Web.Attributes

@model IEnumerable<Kztek.Model.Models.Role>

@{
    ViewBag.Title = "Index";
}

@{
    ViewBag.Title = "Vai trò";
    string controller = this.ViewContext.RouteData.Values["controller"].ToString();
}

<div class="page-header">
    <h1>
        Danh sách vai trò
    </h1>
</div>

<div class="row">
    @using (Html.BeginForm("Index", "Role", FormMethod.Get, new { id = "frmRole" }))
    {
        <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12 divboxmd">
            <input type="text" name="key" value="" placeholder="Từ khóa..." class="form-control" />
        </div>
        <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12 divboxmd">
            @Html.Action("Actions", "Home", new { ActionName = "Search", ControllerName = controller })

            @Html.Action("Actions", "Home", new { ActionName = "Index", ControllerName = controller })
        </div>
    }
</div>

<div class="hr hr-18 dotted hr-24"></div>

<div class="row">
    <div class="col-xs-12">
        @Html.Action("Actions", "Home", new { ActionName = "Create", ControllerName = controller })
    </div>
</div>

<div class="hr hr-18 dotted hr-24"></div>

<div class="row">
    <div class="col-xs-12">
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
                <tr>
                    <th class="center hidden-480">Id</th>
                    <th class="center">Tên vai trò</th>
                    <th class="center hidden-480">Mô tả</th>
                    <th class="center hidden-480">Trạng thái</th>
                    <th class="center">Xử lý</th>
                </tr>
            </thead>

            <tbody>
                @if (Model.Any())
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-left hidden-480">
                                @item.Id
                            </td>

                            <td class="text-left">
                                @item.RoleName
                            </td>

                            <td class="text-left hidden-480">
                                @item.Description
                            </td>

                            <td class="center hidden-480">
                                @if (item.Active == true)
                                {
                                    <span class="label label-sm label-success">Kích hoạt</span>
                                }
                                else
                                {
                                    <span class="label label-sm label-warning">Chưa kích hoạt</span>
                                }
                            </td>
                            <td class="center">
                                <div class="btn-group">
                                    @Html.Action("Actions", "Home", new { ActionName = "Update", ControllerName = controller, id = item.Id })
                                    @Html.Action("Actions", "Home", new { ActionName = "Delete", ControllerName = controller, id = item.Id })
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div><!-- /.span -->
</div><!-- /.row -->
@section scripts{
    <script>
        $(document).ready(function () {
            SearchSubmit("frmRole");

            DeleteSubmit('/Admin/Role/Delete');
        });
    </script>
    }

Kztek.Web/Views/Role/MenuFunctionChild.cshtml
@using Kztek.Model.Models

@model List<Kztek.Model.Models.MenuFunction>

@{
    var listMenuFunction = (List<Kztek.Model.Models.MenuFunction>)ViewBag.MenuList;
    var lstRoleMenu = (List<Kztek.Model.Models.RoleMenu>)ViewBag.RoleMenuList;
}

@if (Model.Any())
{
    <ul style="display:none" class="submenu1">
        @foreach (var item in Model.OrderBy(n => n.OrderNumber))
        {
            var child = listMenuFunction.Any(n => n.ParentId.Equals(item.Id));
            if (child)
            {
                if (lstRoleMenu != null && lstRoleMenu.Any(n => n.MenuId.Equals(item.Id)))
                {
                    <li>
                        <i class="ace-icon fa fa-plus-circle"></i>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" checked />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                        @Html.Action("MenuFunctionChild", "Role", new { parentid = item.Id, roleid = ViewBag.RoleId })
                    </li>
                }
                else
                {
                    <li>
                        <i class="ace-icon fa fa-plus-circle"></i>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                        @Html.Action("MenuFunctionChild", "Role", new { parentid = item.Id, roleid = ViewBag.RoleId })
                    </li>
                }

            }
            else
            {
                if (lstRoleMenu != null && lstRoleMenu.Any(n => n.MenuId.Equals(item.Id)))
                {
                    <li>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" checked />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                    </li>
                }
                else
                {
                    <li>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                    </li>
                }
            }
        }
    </ul>
}

Kztek.Web/Views/Role/MenuFunctionList.cshtml
@model List<Kztek.Model.Models.MenuFunction>

@{
    string selected = (string)ViewBag.Selected;
}

@if (Model.Any())
{
    var count = 0;
    <ul class="treeCustom">
        @foreach (var item in Model.OrderBy(n => n.OrderNumber))
        {
            count++;
            if (selected.Contains(item.Id.ToString()))
            {
                <li>
                    <label class="line-height-250">
                        <input type="checkbox" name="chkCheckBox" id="chkCheckBox" value="@item.Id" class="ace chkCheckBox" checked />
                        <strong class="lbl" style="font-weight:bold;"> </strong>
                    </label>
                    <span class="liMenuFunction" style="font-weight: bold;">
                        @item.MenuName
                    </span>
                    @Html.Action("Child", new { parentId = item.Id.ToString(), selectedId = selected })
                </li>
            }
            else
            {
                <li>
                    <label class="line-height-250">
                        <input type="checkbox" name="chkCheckBox" id="chkCheckBox" value="@item.Id" class="ace chkCheckBox" />
                        <strong class="lbl" style="font-weight:bold;"></strong>
                    </label>
                    <span class="liMenuFunction" style="font-weight: bold;">
                        @item.MenuName
                    </span>
                    @Html.Action("Child", new { parentId = item.Id.ToString(), selectedId = selected })
                </li>
            }
        }
    </ul>
}

Kztek.Web/Views/Role/MenuFunctionParent.cshtml
@model List<Kztek.Model.Models.MenuFunction>

@{
    var lstRoleMenu = (List<Kztek.Model.Models.RoleMenu>)ViewBag.RoleMenuList;
}

@if (Model.Any())
{
    <ul class="treeCustom" style="list-style-type:none">
        @foreach (var item in Model.Where(n => n.ParentId == "0").OrderBy(n => n.OrderNumber))
        {
            var child = Model.Any(n => n.ParentId.Equals(item.Id));
            if (child)
            {
                if (lstRoleMenu != null && lstRoleMenu.Any(n => n.MenuId.Equals(item.Id)))
                {
                    <li>
                        <i class="ace-icon fa fa-plus-circle"></i>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" checked />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                        @Html.Action("MenuFunctionChild", "Role", new { parentid = item.Id, roleid = ViewBag.RoleId })
                    </li>
                }
                else
                {
                    <li>
                        <i class="ace-icon fa fa-plus-circle"></i>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                        @Html.Action("MenuFunctionChild", "Role", new { parentid = item.Id, roleid = ViewBag.RoleId })
                    </li>
                }
            }
            else
            {
                if (lstRoleMenu != null && lstRoleMenu.Any(n => n.MenuId.Equals(item.Id)))
                {
                    <li>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" checked />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                    </li>
                }
                else
                {
                    <li>
                        <label>
                            <input type="checkbox" name="chkCheckBoxValue" class="chkCheckBoxValue ace" value="@item.Id" />
                            <span class="liMenuName lbl">@item.MenuName</span>
                        </label>
                    </li>
                }
            }
        }
    </ul>
}

Kztek.Web/Views/Role/Update.cshtml
@model Kztek.Model.Models.Role

@{
    ViewBag.Title = "Cập nhật vai trò";

    string selected = (string)ViewBag.Selected;
}

<div class="page-header">
    <h1>
        @ViewBag.Title
    </h1>
</div>
<div class="row">
    @if (TempData["Success"] != null)
    {
        <strong style="color:green">@TempData["Success"]</strong>
    }
    <strong style="color:red">@ViewBag.Error</strong>
</div>
<div class="row">
    <div class="col-md-7 col-xs-12">
        <h3 class="header smaller lighter blue">Thông tin cơ bản</h3>
        @using (Html.BeginForm("Update", "Role", FormMethod.Post, new { encType = "multipart/form-data", @class = "form-horizontal", @role = "form", @id = "frmUpdateRole" }))
        {
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Tên vai trò <span style="color:red">*</span></label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.RoleName, new { @class = "form-control", @placeholder = "Tên vai trò" })
                    @Html.ValidationMessageFor(n => n.RoleName, "", new { @class = "text-danger" })
                    @Html.HiddenFor(n => n.Id)
                    @Html.Hidden("menufunctionvalues")
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Mô tả </label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Description, new { @class = "form-control", @placeholder = "Mô tả" })
                    @Html.ValidationMessageFor(n => n.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Kích hoạt </label>
                <div class="col-sm-6">
                    <label class="line-height-250">
                        @Html.CheckBoxFor(n => n.Active, new { @class = "ace", @checked = "true" })
                        <span class="lbl"></span>
                    </label>
                </div>
            </div>

            @Html.Action("Buttons", "Home", new { controller = "Role", action = "Update", url = ViewBag.urlValue })
        }
    </div>
    <div class="col-md-5 col-xs-12">
        <h3 class="header smaller lighter blue">Danh mục hệ thống</h3>
        <div style="overflow-y:scroll;height:400px;position:relative">
            @Html.Action("MenuFunctionList", "Role", new { str = selected })
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $(".chkCheckBox").click(function () {
                var cmd = $(this);
                cmd.parent().parent().find('ul li input[type=checkbox]').prop('checked', cmd.is(':checked'));
            });

            $("span.liMenuFunction").click(function () {
                var cmd = $(this);
                cmd.parent().find('ul li span.liMenuFunction').parent().parent().fadeToggle();
            });

            $("#frmUpdateRole").submit(function () {
                var str = "";
                $("input[name='chkCheckBox']").each(function () {
                    var cmd = $(this);
                    var id = cmd.prop("value");
                    if ($(this).is(":checked")) {
                        str = str + id + ",";
                    }
                });
                $("#menufunctionvalues").val(str);
            });
        });
    </script>
}