Kztek.Web/Controllers/StudentController.cs
using Kztek.Model.Models;
using Kztek.Service.Admin;
using Kztek.Web.Core.Functions;
using Kztek.Web.Core.Helpers;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kztek.Web.Controllers
{
    public class StudentController : Controller
    {
        

        private IStudentService _StudentService;

        public StudentController (IStudentService StudentService)
        {
            this._StudentService = StudentService;
            
        }
        // GET: Student
        public ActionResult Index(string key , int page = 1)
            {

            int pageSize = 1;


            // Laays phan trang

            var list = _StudentService.GetAllPagingByFirst (key, page, pageSize);
            //Đổ lên grid

            var gridModel = PageModelCustom<Student>.GetPage(list  , page , pageSize);
            //ViewBag
            ViewBag.keyValue = key;
            return View(gridModel);
        }
        [HttpGet]
        public ActionResult Create()
        {   
            return View();
        }
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file ,Student student,  bool SaveAndCountinue = false)
        {

            //File upload
            if (file != null  && file.ContentLength > 0)
            {
                var extension = Path.GetExtension(file.FileName) ?? "";
                var fileName = Path.GetFileName(string.Format("{0}{1}", StringUtil.RemoveSpecialCharactersVn(file.FileName.Replace(extension, "")).GetNormalizeString(), extension));
                student.UserAvatar = string.Format("{0}{1}", ConfigurationManager.AppSettings["uploadfolder"], fileName);
            }


            // Kiêm tra
            if (!ModelState.IsValid)
            {
                return View(student);
            }   
            // Gán giá trị
            student.Id = Common.GenerateId();




            // Thêm mới
            var result = _StudentService.Create(student);
            var selectedGender = student.Gender;
            if (result.isSuccess)
            {


                if (SaveAndCountinue)
                {
                    TempData["Success"] = result.Message;
                    return RedirectToAction("Action");

                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(student);
            }
        }
        [HttpGet]
        public ActionResult Update ( string id)
        {
            var result = _StudentService.GetById(id);
            return View(result);
        }
        [HttpPost]
        public ActionResult Update (Student  obj , HttpPostedFileBase file)
                    {

            string error = string.Empty;
            //Kiểm tra
            //var oldObj = _StudentService.GetById(obj.Id);
            //if (oldObj == null)
            //{
            //    ViewBag.Error = "Bản ghi không tồn tại";
            //    return View(obj);
            //}
            //if (!ModelState.IsValid)
            //{
            //    return View(oldObj);
            //}

            //var isExisted = _StudentService.GetByFullName_Id(oldObj.Fullname, oldObj.Id.ToString());
            //if (isExisted != null)
            //{
            //    ModelState.AddModelError("FullName", "Ho và Ten đã có");
            //    return View(oldObj);
            //}
            ////Gấn giá trị

            //oldObj.Fullname = obj.Fullname;
            //oldObj.Active = obj.Active;
            //File upload
            //if (file != null)
            //{
            //    var extension = Path.GetExtension(file.FileName) ?? "";
            //    var fileName = Path.GetFileName(string.Format("{0}{1}", StringUtil.RemoveSpecialCharactersVn(file.FileName.Replace(extension, "")).GetNormalizeString(), extension));
            //    obj.UserAvatar = string.Format("{0}{1}", ConfigurationManager.AppSettings["uploadfolder"], fileName);

            if (file != null)
            {
                obj.UserAvatar = string.Format("{0}/{1}", ConfigurationManager.AppSettings["uploadfolder"], Common.UploadImages(out error, Server.MapPath(ConfigurationManager.AppSettings["uploadfolder"]), file));
            }


            //Thực hiện cập nhật
            var result = _StudentService.Update(obj);
            if (result.isSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(obj);
            }
        }
 
        public JsonResult Delete (string id)
        {
          
            var result = _StudentService.DeleteById(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
    }

Kztek.Web/Views/Student/Create.cshtml
@model Kztek.Model.Models.Student
@{
    ViewBag.Title = "Thêm mới sinh viên";
}

<div class="page-header">
    <h1>
        @ViewBag.Titile
    </h1>

</div>
<div class="row">

    @if(TempData["Success"]!= null)
    {
        <strong style="color:green">@TempData["Success"]</strong>
    }
    <strong style="color: red"> @ViewBag.Error</strong>
</div>

<div class="row">
    <div class="col-md-8 col-xs-12">
        <h3 class="header smaller lighter blue">Thông tin cơ bản </h3>
        @using (Html.BeginForm("Create", "Student", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", @role = "form", @id = "frmCreateUser" }))
        {

            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Họ và Tên <span style="color:red">*</span></label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Fullname, new { @class = "form-control", @placeholder = "Họ Và Tên" })

                </div>
            </div>

            <div><br /></div>
            <div><br /></div>
            <div><br /></div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Email <span style="color:red">*</span></label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Email, new { @class = "form-control" })

                </div>
            </div>
            <div><br /></div>
            <div><br /></div>

            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Số Điện Thoại  <span style="color:red">*</span></label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Phone, new { @class = "form-control" })

                </div>
            </div>
            <div><br /></div>
            <div><br /></div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Ngày Sinh</label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Birthday, new { @class = "form-control" })

                </div>
            </div>
            <div><br /></div>
            <div><br /></div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right">Giới tính</label>
                <div class="col-sm-6 col-xs-12">
                    @Html.DropDownListFor(n => n.Gender, Kztek.Model.Models.Student.GetGenderSelectItems(), "Select Gender")
                </div>
            </div>

            <div><br /></div>
            <div><br /></div>

            <div class="form-group">
                <label class="col-sm-4 control-label" no- padding- right>Kích hoạt</label>
                <div class="col-sm-6">
                    <label class="line-height-250">
                        @Html.CheckBoxFor(n => n.Active, new { @class = "ace", @checked = "checked" })
                        <span class="lbl"></span>
                    </label>
                </div>
            </div>
            <div class="form-group">
                @*<label class="col-sm-4 control-label no-padding-right"> Ảnh đại diện </label>
        <div class="col-sm-6">
            <input type="file" name="file" id="file" />
        </div>*@
                
                <label class="col-sm-4 control-label no-padding-right" for="file">Ảnh đại diện</label>
                <div>
                <input type="file" name="file" id="file" /><br><br>
            </div>
            </div>
            @Html.Action("Buttons", "Home", new { controller = "Student", action = "Create", url = ViewBag.urlValue })

        }
    </div>
        </div>

        

Kztek.Web/Views/Student/Delete.cshtml
@model  Kztek.Model.Models.Student
    ViewData["Title"] = "Delete";
}
<h2>delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.HiddenFor(model => model.Id)
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <div>
            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>
        </div>
        <dt>
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fullname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

    </dl>
    @using (Html.BeginForm("Delete","Student"))
    {

        <div class="form-actions no-color">
            <div id="Click"></div>
            <div id="show"></div>
            <button type="button" class="btn btn-default" name="btnShow">Click</button>
            <button type="button" class="btn btn-default" name="btnUpdate">Delete</button>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Kztek.Web/Views/Student/Index.cshtml
    @using Kztek.Model.CustomModel
@using Kztek.Web.Core.Extensions
@model PageModel<Kztek.Model.Models.Student>
@{
    ViewBag.Title = "Hệ thống";
    string controller = this.ViewContext.RouteData.Values["controller"].ToString();

}

<div class="page-header">
    <h1>
        Danh sách sinh viên
    </h1>


</div>

<div class="row">
    @using (Html.BeginForm("Index", "Student", FormMethod.Get , new { id ="frmStudent"}))
    {
        <div class="col-md-3 col-lg-3 col-xs-12 col-sm-12 divboxmd">
            <input type="text" name="key" value="@ViewBag.keyValue" placeholder="Từ khóa..." class="form-control" />
        </div>
        <div class="col-md-3 col-lg-3 col-xs-12 col-sm-12 divboxmd">
            @Html.Action("Actions", "Home", new { ActionName = "Search", ControllerName = controller })
            @Html.Action("Actions", "Home", new { ActionName = "Index", ControllerName = controller })


        </div>
    }
</div>

<div class="hr hr-18 dotted hr-24"></div>

<div class="row">
    <div class="col-xs-12">
         @Html.Action("Actions", "Home", new  { ActionName = "Create", ControllerName = controller })
    </div>
</div>

<div class="hr hr-18 dotted hr-24"></div>
<div class="row">
    <div class="col-xs-12">
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
                <tr>
                    <th class="center hidden-480">Id</th>
                    <th class="center">Tên người dùng</th>
                    <th class="center hidden-480">Email</th>
                    <th class="center hidden-480">Số điện thoại</th>
                    <th class="center hidden-480">Giới tính</th>
                    <th class="center hidden-480">Birthday</th>
                    <th class="center hidden-480">Trạng thái</th>
                    <th class="center">Xử lý</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Data.Any())
                {
                    foreach (var item in Model.Data)
                    {
                <tr>
                    <td class="text-left hidden-480">
                        @item.Id
                    </td>
                    <td class="text-left hidden-480">
                        @item.Fullname
                    </td>
                    <td class="text-left hidden-480"> 
                        @item.Email
                    </td>
                    <td class="text-left hidden-480">
                         @item.Phone
                    </td>
                    <td class="text-left hidden-480">
                        @item.Gender
                    </td>
                    <td class="text-left hidden-480">
                    @if (item.Birthday != null)
                    {
                        <span> @Convert.ToDateTime(item.Birthday).ToString("dd/MM/yyyy")</span>
                    }
                    </td>
                    <td class="text-left hidden-480">
                        @if (item.Active == true)
                        {
                            <span class="label label-sm label-success">Kích hoạt</span>
                        }
                        else
                        {
                            <span class="label label-sm label-warning">Chưa kích hoat</span>
                        }
                    </td>
                    <td class="center">
                        <div class="btn-group">
                            @Html.Action("Actions", "Home", new { ActionName = "Update", ControllerName = controller, id = item.Id })

                            @Html.Action("Actions", "Home", new { ActionName = "Delete", ControllerName = controller, id =  item.Id })
                        </div>

                    </td>
                </tr>

                    }
                }
            </tbody>
        </table>
    </div>

    @if (Model.Data.Any())

    {

        <div class="col-xs-12">
            <div class="pull-right">
                @Html.GeneratePagingFooter(Model.TotalPage,  Model.PageIndex, Model.PageSize, "pagination", x => Url.Action("Index", "Student", new
           {

               page = x,
               key = ViewBag.keyValue,

           }))
            </div>
        </div>
    }


</div>
@section scripts{
    <script>
        $(document).ready(function () {

            $('button[name=btnFilter]').click(function () {
                $('#frmStudent').submit();
            });



            $('.btnDelete').click(function () {
                var cmd = $(this);
                var _id = cmd.attr('idata');

                bootbox.confirm("Bạn chắc chắn muốn xóa bản ghi này?", function (result) {
                    if (result) {
                        $.ajax({
                            url: ('/Student/Delete'),
                            data: { id: _id },
                            type: 'json',
                            //async:false,
                            success: function (data) {
                                $('#frmStudent').load("/Student");

                                if (data.isSuccess) {

                                    bootbox.success(data.Message,"Xóa thành công")
                                    cmd.parent().fadeOut();
                                } else {
                                    toastr.error(data.Message, 'Không xóa được  ');
                                }
                            }
                        });
                    }
                });
            });
        })
    </script>
    
    }

Kztek.Web/Views/Student/Update.cshtml
@using Kztek.Web.Core.Extensions

@model Kztek.Model.Models.Student

@{
    ViewBag.Title = "Cập nhật người dùng";


}

<div class="page-header">
    <h1>
        @ViewBag.Title
    </h1>
</div>
<div class="row">
    @if (TempData["Success"] != null)
    {
        <strong style="color:green">@TempData["Success"]</strong>
    }
    <strong style="color:red">@ViewBag.Error</strong>
</div>
<div class="row">
    <div class="col-md-8 col-xs-12">
        <h3 class="header smaller lighter blue">Thông tin cơ bản</h3>
        @using (Html.BeginForm("Update", "Student", FormMethod.Post, new { encType = "multipart/form-data", @class = "form-horizontal" }))
        {
            @*@Html.ValidationSummary(false, "", new { @class = "text-danger" })*@
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Họ Và Tên <span style="color:red">*</span></label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Fullname, new { @class = "form-control", @placeholder = "Họ và Tên " })
                    @Html.ValidationMessageFor(n => n.Fullname, "", new { @class = "text-danger" })


                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Email </label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Email, new { @class = "form-control", @type = "phone" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Phone </label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Phone, new { @class = "form-control", @type = "phone" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Ngày Sinh </label>
                <div class="col-sm-6 col-xs-12">
                    @Html.TextBoxFor(n => n.Birthday, new { @class = "form-control", @type = "birthday" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right">Giới tính</label>
                <div class="col-sm-6 col-xs-12">
                    @Html.DropDownListFor(n => n.Gender, Kztek.Model.Models.Student.GetGenderSelectItems(), "Select Gender")
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Kích hoạt </label>
                <div class="col-sm-6">
                    <label class="line-height-250">
                        @Html.CheckBoxFor(n => n.Active, new { @class = "ace", @checked = "true" })
                        <span class="lbl"></span>
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right"> Ảnh đại diện </label>
                <div class="col-sm-6">
                    <input type="file" name="file" id="file" />
                </div>

            </div>

            @Html.Action("Buttons", "Home", new { controller = "Student", action = "Update", url = ViewBag.urlValue })
        }
    </div>

</div>

@section scripts{
    <script>

    </script>
}